# Generated by Django 4.0.4 on 2022-05-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=20)),
                ('Cognome', models.CharField(max_length=20)),
                ('Email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('immagine', models.ImageField(upload_to='')),
                ('titolo', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('disponibile', models.BooleanField(default=True)),
                ('quantità', models.IntegerField(default=1)),
                ('scheda_tecnica', models.CharField(max_length=200)),
                ('prezzo', models.FloatField()),
                ('fornitore', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.fornitori')),
            ],
        ),
        migrations.CreateModel(
            name='Recensioni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user_recensione', models.IntegerField(default=1)),
                ('stelle', models.IntegerField(default=1)),
                ('descrizione', models.CharField(max_length=300)),
                ('prodotto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.prodotti')),
            ],
        ),
    ]
