# Generated by Django 4.0.4 on 2022-05-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquirenti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=20)),
                ('Cognome', models.CharField(max_length=20)),
                ('Email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='recensioni',
            name='id_user_recensione',
        ),
        migrations.AddField(
            model_name='recensioni',
            name='user_recensione',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.acquirenti'),
        ),
    ]
