# Generated by Django 4.0.4 on 2022-05-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_prodotti_media_valutazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotti',
            name='vendite',
            field=models.IntegerField(default=0),
        ),
    ]
