# Generated by Django 4.0.4 on 2022-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_prodotti_vendite'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquirenti',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
