# Generated by Django 4.0.4 on 2022-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_acquirenti_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitori',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
