# Generated by Django 4.0.4 on 2022-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_recensioni_user_recensione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensioni',
            name='stelle',
            field=models.FloatField(default=0),
        ),
    ]
