# Generated by Django 4.0.4 on 2022-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_recensioni_stelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotti',
            name='media_valutazione',
            field=models.FloatField(default=0),
        ),
    ]
