# Generated by Django 4.0.4 on 2022-05-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_prodotti_media_valutazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='scheda_tecnica',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categorie'),
        ),
    ]
