# Generated by Django 4.0.4 on 2022-05-15 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0011_categorie_alter_prodotti_scheda_tecnica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotti',
            name='vendite',
        ),
        migrations.CreateModel(
            name='Vendite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantità', models.IntegerField(default=0)),
                ('acquistatore', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_acquistatore', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_fornitore', to=settings.AUTH_USER_MODEL)),
                ('prodotto_venduto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.prodotti')),
            ],
        ),
    ]
