# Generated by Django 4.0.4 on 2022-05-30 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0013_alter_vendite_acquistatore_alter_vendite_fornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecensoniFornitori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recensione', models.CharField(max_length=300)),
                ('stelle', models.FloatField(default=0)),
                ('fornitore', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_fornitore', to=settings.AUTH_USER_MODEL)),
                ('user_recensione', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
