# Generated by Django 4.0.4 on 2022-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_blacklist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.CharField(max_length=300),
        ),
    ]
