# Generated by Django 4.0.4 on 2022-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_blacklist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotti',
            name='scheda_tecnica',
            field=models.CharField(max_length=2000),
        ),
    ]
