# Generated by Django 4.0.4 on 2022-06-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_prodotti_scheda_tecnica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acquirenti',
        ),
        migrations.DeleteModel(
            name='Fornitori',
        ),
    ]
